version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    depends_on:
      - mongo
    ports:
      - 3000:3000
  mongo:
    image: mongo:4.2
    expose:
      - 27017
    ports:
    - 30000:27017
    volumes:
      - ../data/db:/data/db_docker
    command: --bind_ip_all